### ISSUE TITLE
Not Being Added to the Member Process Queue

### ISSUE THREAD

**Issue by davidshq** [LiquidChurch/groups-help#7]
I signed up for a small group at Somerset earlier today but am not seeing myself in the Liquid Groups: Member Process (Somerset) queue.

**Comment by nwoeddie** [comment]
You are added to a form called "CONTACTED A GROUP LEADER (SOMERSET)". Once the coordinator matches you to a CCB profile, you will be automatically added to the queue.

![mackey](https://user-images.githubusercontent.com/8533760/35643435-3bdae2f0-0694-11e8-85d6-c4e80e5cf5f3.png)

**Comment by davidshq** [comment]
Got it, I forgot you were submitting via the form and we weren't hooking directly into the queue.
